import { Injectable } from '@nestjs/common';
import { ValidationError } from '@esg/shared-kernel';
import { ReportService } from '../../reporting/services/report.service';
import type { ReportSection } from '../../reporting/services/report.service';

/**
 * Generates iXBRL (inline XBRL) HTML documents per ESEF format.
 * Each numeric data point is wrapped in <ix:nonFraction>.
 * Each narrative disclosure is wrapped in <ix:nonNumeric>.
 */
@Injectable()
export class XbrlService {
  constructor(private readonly reportService: ReportService) {}

  async generateIxbrl(reportId: string): Promise<string> {
    const report = await this.reportService.findById(reportId);
    if (report.status !== 'finalized') {
      throw new ValidationError('Report must be finalized before generating iXBRL.');
    }

    const m = report.metadata;
    const periodRef = 'FY' + new Date().getFullYear();

    let html = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ix="http://www.xbrl.org/2013/inlineXBRL"
      xmlns:ixt="http://www.xbrl.org/inlineXBRL/transformation/2022-02-01"
      xmlns:esrs="http://xbrl.efrag.org/taxonomy/esrs/2024"
      xmlns:xbrli="http://www.xbrl.org/2003/instance"
      xmlns:link="http://www.xbrl.org/2003/linkbase"
      xmlns:xlink="http://www.w3.org/1999/xlink"
      xml:lang="en">
<head>
  <meta charset="UTF-8" />
  <title>${this.escapeHtml(m.name)} — iXBRL Report</title>
  <style>
    body { font-family: 'Times New Roman', serif; max-width: 900px; margin: 2rem auto; color: #1f2937; line-height: 1.6; }
    h1 { font-size: 1.8rem; border-bottom: 2px solid #1e40af; padding-bottom: 0.5rem; }
    h2 { font-size: 1.3rem; color: #1e40af; margin-top: 2.5rem; border-bottom: 1px solid #dbeafe; padding-bottom: 0.25rem; }
    table { width: 100%; border-collapse: collapse; margin: 1rem 0; }
    th, td { padding: 0.5rem; border: 1px solid #d1d5db; text-align: left; }
    th { background: #f3f4f6; font-weight: bold; }
    td.numeric { text-align: right; font-variant-numeric: tabular-nums; }
    .narrative { margin: 1rem 0; text-align: justify; }
    .ix-tagged { background: #fef3c7; border-bottom: 1px dashed #f59e0b; }
    .footer { margin-top: 3rem; font-size: 0.8rem; color: #6b7280; border-top: 1px solid #e5e7eb; padding-top: 1rem; }
  </style>
</head>
<body>
  <ix:header>
    <ix:hidden>
      <ix:references>
        <link:schemaRef xlink:type="simple"
          xlink:href="http://xbrl.efrag.org/taxonomy/esrs/2024/esrs_all.xsd" />
      </ix:references>
      <xbrli:context id="${periodRef}">
        <xbrli:entity>
          <xbrli:identifier scheme="http://www.example.com">${m.name}</xbrli:identifier>
        </xbrli:entity>
        <xbrli:period>
          <xbrli:startDate>${new Date().getFullYear()}-01-01</xbrli:startDate>
          <xbrli:endDate>${new Date().getFullYear()}-12-31</xbrli:endDate>
        </xbrli:period>
      </xbrli:context>
    </ix:hidden>
  </ix:header>

  <h1>${this.escapeHtml(m.name)}</h1>
  <p>European Sustainability Reporting Standards (ESRS) Disclosure</p>
  <p>Reporting Period: ${periodRef} | Format: iXBRL/ESEF</p>
`;

    for (const section of m.sections) {
      html += this.generateSectionIxbrl(section, periodRef);
    }

    html += `
  <div class="footer">
    <p>This document is formatted in iXBRL (inline eXtensible Business Reporting Language) in accordance
    with the European Single Electronic Format (ESEF) regulation. Machine-readable XBRL tags are embedded
    within the HTML to enable automated processing by regulatory authorities.</p>
    <p>Generated by EU ESG Platform on ${new Date().toISOString().split('T')[0]}</p>
  </div>
</body>
</html>`;

    return html;
  }

  private generateSectionIxbrl(section: ReportSection, periodRef: string): string {
    let html = `\n  <h2>${section.standardCode} — ${this.escapeHtml(section.standardName)}</h2>\n`;

    // Data points table with iXBRL tags
    if (section.dataPoints.length > 0) {
      html += `  <table>\n    <thead><tr><th>Disclosure</th><th>Value</th><th>Unit</th></tr></thead>\n    <tbody>\n`;

      for (const dp of section.dataPoints) {
        const tagName = `esrs:${dp.metricCode}`;
        const unitRef = this.normalizeUnit(dp.unit);

        if (dp.value !== null) {
          html += `    <tr>
      <td>${this.escapeHtml(dp.metricName)}</td>
      <td class="numeric"><ix:nonFraction name="${tagName}" contextRef="${periodRef}"${unitRef ? ` unitRef="${unitRef}"` : ''} decimals="2" class="ix-tagged">${dp.value.toLocaleString()}</ix:nonFraction></td>
      <td>${this.escapeHtml(dp.unit || '')}</td>
    </tr>\n`;
        } else {
          html += `    <tr><td>${this.escapeHtml(dp.metricName)}</td><td class="numeric">—</td><td>${this.escapeHtml(dp.unit || '')}</td></tr>\n`;
        }
      }

      html += `    </tbody>\n  </table>\n`;
    }

    // Narrative with iXBRL tag
    if (section.narrative) {
      const narrativeTag = `esrs:${section.standardCode}_Narrative`;
      html += `  <div class="narrative">
    <ix:nonNumeric name="${narrativeTag}" contextRef="${periodRef}" class="ix-tagged">${this.escapeHtml(section.narrative)}</ix:nonNumeric>
  </div>\n`;
    }

    return html;
  }

  private normalizeUnit(unit: string | null): string {
    if (!unit) return '';
    const unitMap: Record<string, string> = {
      'tCO2e': 'iso4217:EUR_tCO2e',
      'MWh': 'esrs:MWh',
      'ML': 'esrs:megalitres',
      'tonnes': 'esrs:tonnes',
      'headcount': 'esrs:headcount',
      '%': 'xbrli:pure',
      'EUR': 'iso4217:EUR',
      'count': 'xbrli:pure',
      'rate': 'xbrli:pure',
      'days': 'esrs:days',
      'hours': 'esrs:hours',
      'hours/employee': 'esrs:hoursPerEmployee',
      'ratio': 'xbrli:pure',
    };
    return unitMap[unit] || '';
  }

  private escapeHtml(text: string): string {
    return text
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
  }
}
